name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker build -t local - < .github/Dockerfile
      - name: Run build
        run: docker run -i -v $PWD:/build -w/build local ./build.sh

